---
title: "Descriptive Analysis"
author: "Kohei Watanabe"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#Sys.setlocale("LC_ALL","ja_JP.UTF-8")
knitr::opts_chunk$set(echo = TRUE, dpi = 150, fig.height = 5, fig.width = 10,
                      warning = FALSE, message = FALSE)
require(ggplot2)
```

```{r}
dat_lss <- readRDS("result/data_lss.RDS")
dat_lda <- readRDS("result/data_slda.RDS")
dat <- cbind(dat_lda, dat_lss[c("lss")])

dict <- quanteda::dictionary(file = "dictionary.yml")
dat <- subset(dat, topic %in% names(dict$topic))
dat <- subset(dat, speaker %in% c("安倍晋三", "高市早苗"))
dat$speaker <- droplevels(dat$speaker)
dat$topic <- droplevels(dat$topic)
```

## Topic

```{r}
par(mar = c(4, 6, 1, 1), cex = 0.9)
barplot(proportions(table(dat$speaker, dat$topic), 1), 
        beside = TRUE, horiz = FALSE, las = 1,
        legend.text = levels(dat$speaker),
        args.legend = list(x = "topleft", bty = "n")) 

```

## Sentiment

```{r}
dat$lss <- ave(dat$lss, dat$speaker, FUN = function(x) {
  x - mean(x, na.rm = TRUE)
})
```

```{r}
ggplot(dat, aes(speaker, lss)) +
  geom_boxplot() +
  facet_wrap(vars(topic))
```

