---
title: "Dictionary - Geographical Analysis"
author: "Kohei Watanabe"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#Sys.setlocale("LC_ALL","ja_JP.UTF-8")
knitr::opts_chunk$set(echo = TRUE, dpi = 150, fig.height = 5, fig.width = 10,
                      warning = FALSE, message = FALSE)
library(ggplot2)
```

```{r}
dat <- readRDS("result/data_dictionary.RDS")
```

## Convert wide format to long format

```{r}
tmp <- dat[c("docname", "year", "us", "cn", "ru", "kr", "kp")]
tmp <- reshape(tmp, direction = "long", v.names = "count", timevar = "country",
               times = c("us", "cn", "ru", "kr", "kp"),
               varying = c("us", "cn", "ru", "kr", "kp"))
agg <- aggregate(count ~ year + country, tmp, FUN = sum)
```

## Frequency of countries

```{r}
n <- colSums(dat[c("us", "cn", "ru", "kr", "kp")])
barplot(n)
```

```{r}
ggplot(agg, aes(year, count, color = country)) +
  geom_line() +
  geom_vline(xintercept = c(1991, 2012, 2020), linetype = 2) +
  facet_wrap(vars(country))
```
