---
title: "LDA"
author: "Kohei Watanabe"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#Sys.setlocale("LC_ALL","ja_JP.UTF-8")
knitr::opts_chunk$set(echo = TRUE, dpi = 150, fig.height = 5, fig.width = 10,
                      warning = FALSE, message = FALSE)
library(ggplot2)
library(LSX)
```

```{r}
lss <- readRDS("result/lss.RDS")
```

## Polarity words {.tabset}

### Random highlighting

```{r}
textplot_terms(lss, max_highlighted = 50)
```

### Custom highlighting

```{r}
textplot_terms(lss, highlighted = "*政治*")
```

## Document polarity  {.tabset}

```{r}
dat <- readRDS("result/data_lss.RDS")
```

### Distribution

```{r}
hist(dat$lss)
```

### Simple average

```{r}
agg <- aggregate(lss ~ year, dat, FUN = mean)
ggplot(agg, aes(year, lss)) +
  geom_line() +
  geom_vline(xintercept = c(1991, 2012, 2020), linetype = 2)
```

### Local regression

```{r}
smo <- smooth_lss(dat, lss_var = "lss", date_var = "date", engine = "locfit", span = 0.05)
ggplot(smo, aes(date, fit)) +
  geom_line() +
  geom_ribbon(aes(ymin = fit - se.fit * 1.96, ymax = fit + se.fit * 1.96), alpha = 0.5) +
  geom_vline(xintercept = as.Date(c("1991-01-01", "2012-01-01", "2020-01-01")), linetype = 2)
```
