---
title: "Regression Analysis"
author: "Kohei Watanabe"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#Sys.setlocale("LC_ALL","ja_JP.UTF-8")
knitr::opts_chunk$set(echo = TRUE, dpi = 150, fig.height = 5, fig.width = 10,
                      warning = FALSE, message = FALSE)
require(ggplot2)
```

```{r}
dat_lss <- readRDS("result/data_lss.RDS")
dat_lda <- readRDS("result/data_slda.RDS")
dat_dic <- readRDS("result/data_dictionary.RDS")
dat <- cbind(dat_lda, dat_lss[c("lss")], dat_dic[c("us", "cn", "kr", "kp", "jp")])

dict <- quanteda::dictionary(file = "dictionary.yml")
dat <- subset(dat, topic %in% names(dict$topic))
```

## Create varaibles

```{r}
dat$abe <- dat$speaker == "安倍晋三"
dat$dpj <- dat$speaker %in% c("鳩山由紀夫", "菅直人", "野田佳彦")
dat$p91 <- dat$year > 1991
```

## Variance between topics {.tabset}

### Topics only

```{r}
reg0 <- lm(lss ~ topic, dat)
summary(reg0)
```

### Topics and DPJ

```{r}
reg1 <- lm(lss ~ topic + dpj + topic * dpj, dat)
summary(reg1)
```

### Topics and Abe

```{r}
reg2 <- lm(lss ~ topic + abe + topic * abe, dat)
summary(reg2)
```

## Variance within topics {.tabset}

```{r}
dat_sec <- subset(dat, topic %in% c("安全保障", "外交"))
```

### Countries

```{r}
reg3 <- lm(lss ~ us + cn + kp + kr + jp, dat_sec)
summary(reg3)
```

### Countries and Abe

```{r}
reg4 <- lm(lss ~ us * abe + cn * abe + kp * abe + kr * abe + jp * abe, dat_sec)
summary(reg4)
```

