#source("pre/download.R")
source("pre/corpus.R")
source("pre/tokens.R")
source("dictionary.R")
source("lss.R")
source("lda.R")
source("slda.R")

# rmarkdown::render("report/dictionary.Rmd", knit_root_dir = "../")
# rmarkdown::render("report/lss.Rmd", knit_root_dir = "../")
# rmarkdown::render("report/slda.Rmd", knit_root_dir = "../")
# rmarkdown::render("report/regression.Rmd", knit_root_dir = "../")
